[package]
name = "fannkuch"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
packed_simd_2 = { version = "0.3.4"}
rayon = "1.5"

[profile.release]
lto = "fat"
codegen-units = 1